### ISSUE TITLE
Uncaught TypeError: state.request.abort is not a function

### ISSUE THREAD

**Issue by jvpelt** [pqina/filepond#516]
**Describe the bug**
In my Jest test sometimes during destroy(), it generates an error

**Logs**
<details>
TypeError: state.request.abort is not a function
      at Object.abort (node_modules/filepond/dist/filepond.js:5751:18)
      at node_modules/filepond/dist/filepond.js:6169:31
      at Object.abortProcessing (node_modules/filepond/dist/filepond.js:6154:14)
      at node_modules/filepond/dist/filepond.js:6549:16
          at Array.forEach (<anonymous>)
      at Object.ABORT_ALL (node_modules/filepond/dist/filepond.js:6546:37)
      at Object.dispatch (node_modules/filepond/dist/filepond.js:76:29)
      at Object.destroy (node_modules/filepond/dist/filepond.js:12108:17)
      at FilePond.componentWillUnmount (node_modules/react-filepond/dist/react-filepond.js:102:18)
      at callComponentWillUnmountWithTimer (node_modules/react-dom/cjs/react-dom.development.js:19580:12)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:330:27)
</details>

**To Reproduce**
Not really sure why this is happening at this point, my guess it has something to do with rerenders / state updates in React

**Expected behavior**
Not throwing that error would be nice. I've added a PR with a harmless fix for checking if there is an abort function on state.request.

**Stacktraces**
See the logs.

**Information about your project:**
- Error occurs in Jest tests with React testing library and JSDOM.

**Comment by rikschennink** [comment]
Will close this and discuss further in PR.
