### ISSUE TITLE
IE 11 - Object doesn't support this action

### ISSUE THREAD

**Issue by Zwimber** [pqina/filepond#535]
**Describe the bug**
On IE11 this error is thrown for almost every user

**Logs**
![Screenshot 2020-07-03 at 10 38 36](https://user-images.githubusercontent.com/6017921/86450269-8c115680-bd19-11ea-91c5-8dbba397fa08.png)

**To Reproduce**
1. Install IE11.
2. Upload a file with FilePond

**Expected behavior**
Upload file without throwing this error

**Stacktraces**

<details>
  <summary>Object doesn't support this action</summary>
TypeError: Object doesn't support this action
  at dispatch(webpack:/./node_modules/filepond/dist/filepond.js:12792:7)
  at Anonymous function(webpack:/./node_modules/filepond/dist/filepond.js:12813:9)
  at r(webpack:/./node_modules/@sentry/browser/esm/helpers.js:60:13)
  at t.prototype.invokeTask(webpack:/./node_modules/zone.js/dist/zone.js:419:17)
  at e.prototype.runTask(webpack:/./node_modules/zone.js/dist/zone.js:188:25)
  at e.invokeTask(webpack:/./node_modules/zone.js/dist/zone.js:503:21)
  at task(webpack:/./node_modules/zone.js/dist/zone.js:492:25)
  at n.args[0](webpack:/./node_modules/zone.js/dist/zone.js:3034:21)
</details>

**Information about your project:**
- IE11
- Windows
- Filepond 4.11.0

**Comment by Zwimber** [comment]
Should've looked better to the resolved issues...
